# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semanas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomCampos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=0, max_length=8)),
                ('costo_hra_extra', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('descuento_sindical', models.BooleanField()),
                ('activo', models.BooleanField(default=True)),
                ('tipos_semana', models.ManyToManyField(to='semanas.NomTipoSemanas')),
            ],
            options={
                'db_table': 'nom_campos',
                'get_latest_by': 'codigo',
            },
        ),
    ]
