# Generated by Django 4.0 on 2022-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_campos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomcampos',
            name='costo_hra_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
