# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cultivos',
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('activo', models.BooleanField(default=True)),
                ('id_cultivo', models.ForeignKey(db_column='id_cultivo', on_delete=django.db.models.deletion.CASCADE, to='nom_cultivos.cultivos')),
            ],
            options={
                'db_table': 'variedad',
            },
        ),
        migrations.AddConstraint(
            model_name='variedad',
            constraint=models.UniqueConstraint(fields=('codigo', 'id_cultivo'), name='Combinacion codigo-cultivo debe ser unica'),
        ),
    ]
