# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom_campos', '0001_initial'),
        ('semanas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FletesMaquilas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant_carros', models.IntegerField()),
                ('hrs_fletes', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costo_maquila', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('importe_maquila', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('procesada', models.BooleanField(default=False)),
                ('campo_agricola', models.ForeignKey(db_column='id_campo_agricola', on_delete=django.db.models.deletion.CASCADE, to='nom_campos.nomcampos')),
                ('semana', models.ForeignKey(db_column='id_semana', on_delete=django.db.models.deletion.CASCADE, to='semanas.nomsemanas')),
                ('tipo_semana', models.ForeignKey(db_column='id_tipo_semana', on_delete=django.db.models.deletion.CASCADE, to='semanas.nomtiposemanas')),
            ],
            options={
                'db_table': 'fle_maquilas',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
    ]
