# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('nom_campos', '0001_initial'),
        ('semanas', '0001_initial'),
        ('nom_cuadrilleros', '0001_initial'),
        ('nom_labores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomJornales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(blank=True, max_length=2, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('total_dinero', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_hrs_extra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_dinero_hrs_extra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cerrada', models.BooleanField(default=False)),
                ('campo_agricola', models.ForeignKey(db_column='id_campo_agricola', on_delete=django.db.models.deletion.CASCADE, to='nom_campos.nomcampos')),
                ('cuadrillero', models.ForeignKey(db_column='id_cuadrillero', on_delete=django.db.models.deletion.CASCADE, to='nom_cuadrilleros.nomcuadrilleros')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleados.nomempleado')),
                ('labor', models.ForeignKey(db_column='id_labor', on_delete=django.db.models.deletion.CASCADE, to='nom_labores.nomlabores')),
                ('semana', models.ForeignKey(db_column='id_semana', on_delete=django.db.models.deletion.CASCADE, to='semanas.nomsemanas')),
                ('tipo_semana', models.ForeignKey(db_column='id_tipo_semana', on_delete=django.db.models.deletion.CASCADE, to='semanas.nomtiposemanas')),
            ],
            options={
                'db_table': 'nom_jornales',
            },
        ),
    ]
