# Generated by Django 4.0 on 2022-09-28 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elaborar_remision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FletesFacturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=datetime.date(2022, 9, 28))),
            ],
            options={
                'db_table': 'fle_facturas',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='FletesFacturasRemisiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='asignar_factura.fletesfacturas')),
                ('remision', models.ForeignKey(db_column='id_remision', on_delete=django.db.models.deletion.CASCADE, to='elaborar_remision.fletesremisiones')),
            ],
            options={
                'db_table': 'fle_facturas_remision',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='fletesfacturas',
            name='remisiones',
            field=models.ManyToManyField(through='asignar_factura.FletesFacturasRemisiones', to='elaborar_remision.FletesRemisiones'),
        ),
    ]
