# Generated by Django 4.0 on 2022-09-30 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fletesfacturas',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
