# Generated by Django 4.1.7 on 2023-06-26 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_factura', '0002_alter_fletesfacturas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fletesfacturas',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 26)),
        ),
    ]
