# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomTipoSemanas',
            fields=[
                ('tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nom_tipo_semanas',
                'ordering': ['tipo'],
                'get_latest_by': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='NomSemanas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.DecimalField(decimal_places=0, max_digits=2)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('generado', models.BooleanField(default=False)),
                ('tipo_semana', models.ForeignKey(db_column='id_tipo_semana', default=0, on_delete=django.db.models.deletion.CASCADE, to='semanas.nomtiposemanas')),
            ],
            options={
                'db_table': 'nom_semanas',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddConstraint(
            model_name='nomsemanas',
            constraint=models.UniqueConstraint(fields=('anio', 'tipo_semana', 'semana'), name='unico anio tipo semana'),
        ),
    ]
