"""
Django settings for SistemaGSMO project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from unipath import Path
BASE_DIR = Path(__file__).ancestor(3)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c4wxf1l*elve^uibspj*163rxn^t)%dm$^_(0h5go-!(#iz^x&'


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ##################### Usuarios ######################
    'applications.users',
    #################### Facturacion ####################

    'applications.facturacion.home_facturacion',


    # Aplicaciones de Consultas
    'applications.facturacion.consultas.fletes',

    # Aplicaciones de Procesos
    'applications.facturacion.procesos.procesar_maquila',
    'applications.facturacion.procesos.elaborar_remision',
    'applications.facturacion.procesos.asignar_factura',

    # Aplicaciones de Reportes


    # Aplicaciones de Utilerias



    #################### Fletes #########################

    'applications.fletes.home_fletes',

    # Aplicaciones de Catalogos
    'applications.fletes.catalogos.campos_agricolas',
    'applications.fletes.catalogos.cuadrilleros',
    'applications.fletes.catalogos.cultivos',
    'applications.fletes.catalogos.empresas',
    'applications.fletes.catalogos.labores',
    'applications.fletes.catalogos.semanas',
    'applications.fletes.catalogos.ubicaciones',
    'applications.fletes.catalogos.camiones',
    'applications.fletes.catalogos.compania_fletera',
    # Aplicaciones de Consultas
    # Aplicaciones de Procesos
    'applications.fletes.procesos.capturas_fleteras',
    'applications.fletes.procesos.listados_nomina',
    # Aplicaciones de Reportes
    # Aplicaciones de Tarjetas Nomina
    # Aplicaciones de Utilerias

    #################### Flotilla #######################


    #################### Nomina #########################

    'applications.nomina.home_nomina',

    # Aplicaciones de Catalogos
    'applications.nomina.catalogos.campos_agricolas',
    'applications.nomina.catalogos.cuadrilleros',
    'applications.nomina.catalogos.cultivos',
    'applications.nomina.catalogos.empleados',
    'applications.nomina.catalogos.empresas',
    'applications.nomina.catalogos.labores',
    'applications.nomina.catalogos.puestos',
    'applications.nomina.catalogos.semanas',
    'applications.nomina.catalogos.ubicaciones',
    # Aplicaciones de Consultas
    'applications.nomina.consultas.captura_jornales',
    'applications.nomina.consultas.modificacion_jornales',
    # Aplicaciones de Procesos
    # Aplicaciones de Reportes
    # Aplicaciones de Tarjetas Nomina
    # Aplicaciones de Utilerias


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SistemaGSMO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.child('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SistemaGSMO.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
