# Generated by Django 4.0 on 2022-09-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniasFleteras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(error_messages={'unique': 'Ya existe una compañia fletera con este codigo'}, max_length=3, unique=True)),
                ('cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=16, null=True)),
                ('rfc', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'companias_fleteras',
                'get_latest_by': 'codigo',
            },
        ),
    ]
